register(TOOL,
         id    = 'Import ADNMatches',
         name  = _('Import ADNMatches'),
         description =  _('Import ADN match list'),
         version = '0.0.9',
         gramps_target_version = "5.1",
         status = STABLE,
         fname = 'ImportADNMatch.py',
         authors = ["Eric Doutreleau"],
         authors_email = ["eric@doutreleau.fr"],
         category = TOOL_DBPROC,
         toolclass = 'ImportADNMatchTool',
         optionclass = 'ImportADNMatchOptions',
         tool_modes = [TOOL_MODE_GUI],
         )
